config/routes.rb
Property::Application.routes.draw do

  root to: "home#home_page"

  resources :home do
    collection do
      get "contact_us"
      get "property_results"
      get "search_results"
      get "login"
      get "registration"
      get "postrequirement"
      get "listproperty"

    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end

  	def home_page
  	end

  	def contact_us
  	end

  	def property_results
  	end

  	def search_results
  	end



end

app/controllers/property_controller.rb
class PropertyController < ApplicationController
  def login
  end
  def registration
  end
 def test
end
def contact us
end
def search
end
def search1
end
def postrequirement
end
def search_result
end
def listsurproperty
end
 def newcontact
 end
def new
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/property_helper.rb
module PropertyHelper
end

app/views/home/_search_results.html.haml
.container-fluid{:style => "background-color:#FFFFFF"}
  #property-listings.container.container-pad
    .row
      .col-md-12
        .col-xs-12
        %h1 Resultant Home Listings
        %p A snippet I recently used to display homes for a local brokerage. Focused more on images when accessed through mobile
    .row
      .col-xs-2
      .col-xs-8
       
        / End Listing
        / Begin Listing: 209 CHESTNUT HILL AVE
        .brdr.bgc-fff.pad-10.box-shad.btm-mrg-20.property-listing
          .media
            %a.pull-left{:href => "#", :target => "_parent"}
              %img.img-responsive{:alt => "image", :src => "http://images.prd.mris.com/image/V2/1/iwn7qH9r9OPnqTaTTxxb8PBzQHk2EiHU2PBBntt041AZsVsGY-SeUexTMLgRcYSJukrKOwHaYnTVXAsk6RdSmA.jpg", :height => 100, :width => 100} status:active/solid
            .clearfix.visible-xs
            .media-body.fnt-smaller
              %a{:href => "#", :target => "_parent"}
              %h4.media-heading
                %a{:href => "#", :target => "_parent"}
                  BUILDING TITLE
                  %small.pull-right  $1,599,999
                  %small.pull-right view
              %ul.list-inline.mrg-0.btm-mrg-10.clr-535353
                %li 16,581 SqFt
                %li{:style => "list-style: none"} |
                %li 8 Beds
                %li{:style => "list-style: none"} |
                %li 4 Baths
                %li nanakram guda street 5
                %li AgentName : rahul
                %li ContactNo : 8888888888
                %li Listed : 2 days ago
               
              %p.hidden-xs
                Built by qulitative goods
                and well furnished
             
        / End Listing
        / Begin Listing: 704 SAINT GEORGES ST
        .brdr.bgc-fff.pad-10.box-shad.btm-mrg-20.property-listing
          .media
            %a.pull-left{:href => "#", :target => "_parent"}
              %img.img-responsive{:alt => "image", :src => "http://images.prd.mris.com/image/V2/1/7IZk2HTN0AcHnIb7VCvisTUc3kTbn0UyHQlVAlwkNLM3_8UNN8pcgy9u6KVNoRGGH_kdUlpYehdbqzctRNUebg.jpg", :height => 100, :width => 100}status:active/sold
            .clearfix.visible-xs
            .media-body.fnt-smaller
              %a{:href => "#", :target => "_parent"}
              %h4.media-heading
                %a{:href => "#", :target => "_parent"}
                  BUILDING NAME
                  %small.pull-right $1,595,000
                  %small.pull-right view
              %ul.list-inline.mrg-0.btm-mrg-10.clr-535353
                %li 45992 SqFt
                %li{:style => "list-style: none"} |
                %li 4 Beds
                %li{:style => "list-style: none"} |
                %li 5 Baths
                %li hi-tech city street 3
                %li AgentName : naveen
                %li ContactNo : 9955667788
                %li Listed : 5 dats ago
                
              %p.hidden-xs
                It is proud
                to offer this home
        / End Listing
        / Begin Listing: 1220-32 N HOWARD ST
        .brdr.bgc-fff.pad-10.box-shad.btm-mrg-20.property-listing
          .media
            %a.pull-left{:href => "#", :target => "_parent"}
              %img.img-responsive{:alt => "image", :src => "http://images.prd.mris.com/image/V2/1/vGoNjc2jHGb87GlnnDQlf6LxeOUgIOn0bL6Wvn1nEnig2Ntq6W7xN5cOQBZZeNxl9O42DOkHUw0LNnj1ZB2KHA.jpg", :height => 100, :width => 100}status:active/solid
            .clearfix.visible-xs
            .media-body.fnt-smaller
              %a{:href => "#", :target => "_parent"}
              %h4.media-heading
                %a{:href => "#", :target => "_parent"}
                  BUILDING TITLE
                  %small.pull-right $1,500,000
                  %small.pull-right view
              %ul.list-inline.mrg-0.btm-mrg-10.clr-535353
                %li 4,900 SqFt
                %li{:style => "list-style: none"} |
                %li 1 Beds
                %li{:style => "list-style: none"} |
                %li 1 Baths
                %li somaji guda street 1
                %li AgentName:naresh
                %li ContactNo:8899889988
                %li Listed : 1 week ago
               
              %p.hidden-xs
                A once in a lifetime
                opportunity to own a unique live 
             
        / End Listing
        / Begin Listing: 9006 CREFELD ST
        .brdr.bgc-fff.pad-10.box-shad.btm-mrg-20.property-listing
          .media
            %a.pull-left{:href => "#", :target => "_parent"}
              %img.img-responsive{:alt => "image", :src => "http://images.prd.mris.com/image/V2/1/uLp58OH37CTPHxXcgJXYw8zT2u3xg_2XIbFndB6J0WTSAStGBaEV6YsdAseSZTKAdthm0OzG-Ca_EIkoXIEBxw.jpg", :height => 100, :width => 100}status:active/sold
            .clearfix.visible-xs
            .media-body.fnt-smaller
              %a{:href => "#", :target => "_parent"}
              %h4.media-heading
                %a{:href => "#", :target => "_parent"}
                  BUILDING TITLE
                  %small.pull-right $1,295,000
                  %small.pull-right view
              %ul.list-inline.mrg-0.btm-mrg-10.clr-535353
                %li 7,672 SqFt
                %li{:style => "list-style: none"} |
                %li 7 Beds
                %li{:style => "list-style: none"} |
                %li 5 Baths
                %li madhapur x-roads
                %li AgentName : suprith
                %li ContactNo : 8899776633
                %li Listed : few days ago
                
              %p.hidden-xs
                Located in hyderbad,
                recently named by the planning
                association 
              
        / End Listing
        / Begin Listing: 701 W ALLENS LN
        .brdr.bgc-fff.pad-10.box-shad.btm-mrg-20.property-listing
          .media
            %a.pull-left{:href => "#", :target => "_parent"}
              %img.img-responsive{:alt => "image", :src => "http://images.prd.mris.com/image/V2/1/K12MLs4i-e2rsQ-rA6DoCwlysXSrEXZyHtCFkrOLsvK1y2mvbUrlmw5pMXX1laXlnY9_0VU82YeS3EucwIchtg.jpg", :height => 100, :width => 100}status:active/sold
            .clearfix.visible-xs
            .media-body.fnt-smaller
              %a{:href => "#", :target => "_parent"}
              %h4.media-heading
                %a{:href => "#", :target => "_parent"}
                  BUILDING TITLE
                  %small.pull-right $1,175,000
                  %small.pull-right view
              %ul.list-inline.mrg-0.btm-mrg-10.clr-535353
                %li 9,824 SqFt
                %li{:style => "list-style: none"} |
                %li 8 Beds
                %li{:style => "list-style: none"} |
                %li 5 Baths
                %li tarnaka street 8
                %li AgentName : madhu
                %li ContactNo : 8877665544
                %li Listed : 1 month ago
               
              %p.hidden-xs
                A once in a lifetime
                opportunity to live in this grand home

app/views/home/contact_us.html.haml
.container
  .row
    .col-sm-4
      %form.form-horizontal
        %fieldset
        
        .control-group
          %label.control-label Full Name
          .controls
            %input#full-name.input-xlarge{:name => "full-name", :placeholder => "full name", :type => "text"}
              %p.help-block
       
        .control-group
          %label.control-label organization
          .controls
            %input#organization.input-xlarge{:name => "organization", :placeholder => "organization", :type => "text"}
              %p.help-block
       
        .control-group
          %label.control-label phone no
          .controls
            %input.input-xlarge{:id => "phone no", :name => "phone no", :placeholder => "phone no", :type => "integer"}
              %p.help-block it should be 10 digits
        
        .control-group
          %label.control-label City / Town
          .controls
            %input#city.input-xlarge{:name => "city", :placeholder => "city", :type => "text"}
              %p.help-block
        
        .control-group
          %label.control-label email
          .controls
            %input#email.input-xlarge{:name => "email", :placeholder => "email", :type => "text"}
              %p.help-block
        
        .control-group
          %label.control-label query
          .controls
            %input#query.input-xlarge{:name => "query", :placeholder => "query", :type => "text"}
              %p
                .pull-right
        %button.btn.btn.btn-primary{:type => "send"}
          send
    .col-sm-2
      %h6 locality
      %select.form-control
        %option{:value => "locality"} locality
        %option hi-tech
        %option tarnaka
        %option kukatpally
        %option kothaguda
        %option yusfguda
        %option nanakram guda
        %option kphb
        %option ameerpet
        %br
        %br
      .pull-right
        %h6 Property Type
        %select.form-control
          %option{:value => "property type"} property type
          %option plots/land
          %option residentials
          %option agriculture land
          %option villas
          %option form house
        
       
    .col-sm-2
      %h6 Location
      %select.form-control
        %option{:value => "features"} city
        %option hyderbad
        %option mumbai
        %option banglore
        %option chennai
        %option pune

app/views/home/home_page.html.haml
.row
  .col-sm-6
    /%h4{align: "center"}   RESIDENTIAL 
    .body-image1
      /%h4{align: "center"} RESIDENTIAL
      =image_tag "11.jpg",:id =>"property-logo"
    .body-image
      %h4{align: "left"}
        %font{color: "orange"} RESIDENTIAL      
      = link_to "Independent House", property_results_home_index_path, :class => 'customlabel'
      %br
      = link_to "Apartment", property_results_home_index_path, :class => 'customlabel'     
      %br
      = link_to "Independent Villa", property_results_home_index_path, :class => 'customlabel'
      %br
      = link_to "Flat", property_results_home_index_path, :class => 'customlabel'
      %br    
      = link_to "Farm House", property_results_home_index_path, :class => 'customlabel'
      %br
      = link_to "Other Residential", property_results_home_index_path, :class => 'customlabel'
  .col-sm-6
    .body-image1
      =image_tag "23.jpg",:id =>"property-logo"     
    .body-image
      %h4{align: "left"}
        %font{color: "orange"} COMMERCIAL
      = link_to "Commercial Space", property_results_home_index_path, :class => 'customlabel'
      %br       
      = link_to "Office Space", property_results_home_index_path, :class => 'customlabel'
      %br         
      = link_to "IT/Software Technology Park", property_results_home_index_path, :class => 'customlabel'
      %br       
      = link_to "Industrial Space", property_results_home_index_path, :class => 'customlabel'
      %br       
      = link_to "Warehouse", property_results_home_index_path, :class => 'customlabel'
      %br      
      = link_to "Hotel/Resort", property_results_home_index_path, :class => 'customlabel'
.row      
  .col-sm-6
    .body-image1
      =image_tag "36.jpg",:id =>"property-logo"   
    .body-image
      %h4{align: "left"}
        %font{color: "orange"} LAND
      = link_to "Residential Land", property_results_home_index_path, :class => 'customlabel'
      %br       
      = link_to "Commercial Land", property_results_home_index_path, :class => 'customlabel'
      %br        
      = link_to "Industrial Land", property_results_home_index_path, :class => 'customlabel'
      %br
      = link_to "Agricultural Land", property_results_home_index_path, :class => 'customlabel'
      %br       
      = link_to "Farm House Land", property_results_home_index_path, :class => 'customlabel'
      %br       
      = link_to "Land", property_results_home_index_path, :class => 'customlabel' 
  .col-sm-6
    .body-image1
      =image_tag "46.jpg",:id =>"property-logo"   
    .body-image
      %h4{align: "left"}
        %font{color: "orange" } RENT/LEASE
      = link_to "Apartments/Flats", property_results_home_index_path, :class => 'customlabel'
      %br       
      = link_to "Individual Houses", property_results_home_index_path, :class => 'customlabel'
      %br          
      = link_to "Villas", property_results_home_index_path, :class => 'customlabel'
      %br        
      = link_to "Serviced Apartments", property_results_home_index_path, :class => 'customlabel'
      %br
      = link_to "Office Space", property_results_home_index_path, :class => 'customlabel'
      %br
      = link_to "Industrial space", property_results_home_index_path, :class => 'customlabel'

app/views/home/listproperty.html.haml
.container
  .row
    %form.form-vertical
      %fieldset
        %br
        %label.radio-inline
          %input#inlineCheckbox1{:name => "types of operation", :type => "radio", :value => "resedentail"}/
          residentail
        %label.radio-inline
          %input#inlineCheckbox2{:name => "types of operation", :type => "radio", :value => "commercial"}/
          commercial
        %label.radio-inline
          %input#inlineCheckbox3{:name => "types of operation", :type => "radio", :value => "land"}/
          land
          
        %label.radio-inline
          %input#inlineCheckbox4{:name => "types of operation", :type => "radio", :value => "pg/rent"}/
          pg/rent
          %br
         
        %label{:for => ""}
        .row
          .col-xs-2.col-md-2
            %select.form-control
              %option{:value => "property type"} property type
              %option plots
              %option apartments
              %option independent houses
          .col-xs-2.col-md-2
            %select.form-control
              %option{:value => "features"} property features
              %option 1bhk
              %option 2bhk
              %option 3bhk
              %option 2 car parking
              %option swiming pool
          .col-xs-2.col-md-2
            %select.form-control
              %option{:value => "locality"} locality
              %option hi-tech
              %option tarnaka
              %option kukatpally
              %option kothaguda
              %option yusfguda
              %option nanakram guda
              %option kphb
              %option ameerpet
          .col-xs-2.col-md-2
            %select.form-control
              %option{:value => "property facing"} property facing
              %option north
              %option south
              %option east
              %option west
              %option south east
      %br
        .row
          .col-xs-2.col-md-2
            %input.form-control.input-extra.small{:name => "builtup area", :placeholder => "builtup area", :type => "text", :value => ""}/
            to
          .col-xs-2.col-md-2
            %input.form-control.input-extra.small{:name => "to", :placeholder => "builtup area", :type => "text", :value => ""}/
            sqft
      %br
        .row
          .col-xs-2.col-md-2.form-group
            %input#price.form-control{:autofocus => "", :name => "min price", :placeholder => "price", :price => "min price", :required => "", :type => "price"}min price
          .col-xs-2.col-md-2.form-group
            %input#price.form-control{:name => "max price", :placeholder => "price", :price => "max price", :required => "", :to => "", :type => "price"}max price
      %br
        .col-xs-2.col-md-2
          %select.form-control
            %option{:value => "transaction type"} transaction type
            %option resell
            %option new
            %option both
            %br
           
      %br
        .col-xs-2.col-md-2.form-group
          %input#image.form-control{:placeholder => "image", :required => "required", :title => "image", :type => "title"}image
          %br
          %button.btn.btn-primary.pull-right{:type => "browse"}
            browse
          %br
          %input#image.form-control{:placeholder => "title", :required => "required", :title => "title", :type => "title"}title
          %br
         
          %label{:for => "name"}
            description
            %textarea#description.form-control{:cols => "25", :name => "description", :placeholder => "description", :required => "required", :rows => "6"}
          %button.btn.btn-primary.pull-right{:type => "list"}
            list              
            
          
           

app/views/home/login.html.haml
.container{:style => "margin-top:30px"}
  .col-md-4.col-md-offset-4
    .panel.panel-default
      .panel-heading
        %h3.panel-title
          %strong Sign in
      .panel-body
        %form{:role => "form"}
          .form-group
            %label{:for => "exampleInputEmail1"} Username or Email
            %input#exampleInputEmail1.form-control{:placeholder => "Enter email", :style => "border-radius:0px", :type => "email"}
          .form-group
            %label{:for => "exampleInputPassword1"}
              Password
              %a{:href => "/sessions/forgot_password"} (forgot password)
            %input#exampleInputPassword1.form-control{:placeholder => "Password", :style => "border-radius:0px", :type => "password"}
          %button.btn.btn-sm.btn-default{:type => "submit"} Sign in

app/views/home/postrequirement.html.haml
.container
  .row
    %form.form-vertical
      %fieldset
        %label.radio-inline
          %input#inlineCheckbox1{:name => "types of operation", :type => "radio", :value => "resedential"}
          residentail
        %label.radio-inline
          %input#inlineCheckbox2{:name => "types of operation", :type => "radio", :value => "commercial"}
          commercial
        %label.radio-inline
          %input#inlineCheckbox2{:name => "types of operation", :type => "radio", :value => "land"}
          land
        %label.radio-inline
          %input#inlineCheckbox2{:name => "types of operation", :type => "radio", :value => "pg/rent"}
          pg/rent
        %label{:for => ""}
          %br
          %br
        .row
          .col-xs-2.col-md-2
            %select.form-control
              %option{:value => "property type"} property type
              %option plots
              %option apartments
              %option independent houses
          .col-xs-2.col-md-2
            %select.form-control
              %option{:value => "features"} property features
              %option 1bhk
              %option 2bhk
              %option 3bhk
              %option 2 car oarking
              %option swiming pool
          .col-xs-2.col-md-2
            %select.form-control
              %option{:value => "locality"} locality
              %option hi-tech
              %option tarnaka
              %option kukatpally
              %option kothaguda
              %option yusfguda
              %option nanakram guda
              %option kphb
              %option ameerpet
          .col-xs-2.col-md-2
            %select.form-control
              %option{:value => "property facing"} property facing
              %option north
              %option south
              %option east
              %option west
              %option south east
      %br
        .row
          .col-xs-2.col-md-2
            %input.form-control.input-extra.small{:name => "builtup area", :placeholder => "builtup area", :type => "text", :value => ""}
            to
          .col-xs-2.col-md-2
            %input.form-control.input-extra.small{:name => "to", :placeholder => "builtup area", :type => "text", :value => ""}
            sqft
      %br
        .row
          .col-xs-2.col-md-2.form-group
            %input#price.form-control{:autofocus => "", :name => "min price", :placeholder => "price", :price => "min price", :required => "", :type => "price"}min price
          .col-xs-2.col-md-2.form-group
            %input#price.form-control{:name => "max price", :placeholder => "price", :price => "max price", :required => "", :to => "", :type => "price"}max price
      %br
        
      %br
        .col-xs-2.col-md-2.form-group
          %input#title.form-control{:placeholder => "title", :required => "", :title => "title", :to => "", :type => "title"}title
      %br
      .col-xs-2.col-md-2.form-group
        %textarea#description.form-control{:placeholder => "description", :required => "", :title => "description", :to => "", :type => "textarea"}description
        
        %br
      
         
          %button.btn.btn-primary.pull-right{:type => "post"}
            post

app/views/home/property_results.html.haml
.row
  = render "shared/search_box"
  = render "home/search_results"

app/views/home/registration.html.haml
%form.form-horizontal{:action => "", :method => "POST"}
  .col-md-4.col-md-offset-4
    %fieldset
      #legend
        %legend Register
        .control-group
          / Username
          %label.control-label{:for => "username"} Username
          .controls
            %input#username.input-xlarge{:name => "username", :placeholder => "", :type => "text"}
              %p.help-block Username can contain any letters or numbers, without spaces
              .control-group
      / E-mail
      %label.control-label{:for => "email"} E-mail
      .controls
        %input#email.input-xlarge{:name => "email", :placeholder => "", :type => "text"}
          %p.help-block Please provide your E-mail
          .control-group
            / Password
            %label.control-label{:for => "password"} Password
          .controls
        %input#password.input-xlarge{:name => "password", :placeholder => "", :type => "password"}
          %p.help-block Password should be at least 4 characters
    .control-group
      / Password
      %label.control-label{:for => "password_confirm"} Password (Confirm)
      .controls
        %input#password_confirm.input-xlarge{:name => "password_confirm", :placeholder => "", :type => "password"}
          %p.help-block Please confirm password
    .control-group
      / Button
      .controls
        %button.btn.btn-primary Register

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Property
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .container
      .row
        = render "shared/header"
      .row
        = yield
      .row
        = render  "shared/footer.html"
  

app/views/property/.#login.html.erb
ostryalabs@ostryalabs.5768:1397622478

app/views/property/contactus.html.haml
.container
  .row
    .col-sm-4
      %form.form-horizontal
        %fieldset
        
        .control-group
          %label.control-label Full Name
          .controls
            %input#full-name.input-xlarge{:name => "full-name", :placeholder => "full name", :type => "text"}
              %p.help-block
       
        .control-group
          %label.control-label organization
          .controls
            %input#organization.input-xlarge{:name => "organization", :placeholder => "organization", :type => "text"}
              %p.help-block
       
        .control-group
          %label.control-label phone no
          .controls
            %input.input-xlarge{:id => "phone no", :name => "phone no", :placeholder => "phone no", :type => "integer"}
              %p.help-block it should be 10 digits
        
        .control-group
          %label.control-label City / Town
          .controls
            %input#city.input-xlarge{:name => "city", :placeholder => "city", :type => "text"}
              %p.help-block
        
        .control-group
          %label.control-label email
          .controls
            %input#email.input-xlarge{:name => "email", :placeholder => "email", :type => "text"}
              %p.help-block
        
        .control-group
          %label.control-label query
          .controls
            %input#query.input-xlarge{:name => "query", :placeholder => "query", :type => "text"}
              %p
                .pull-right
        %button.btn.btn.btn-primary{:type => "send"}
          send
    .col-sm-2
      %h6 locality
      %select.form-control
        %option{:value => "locality"} locality
        %option hi-tech
        %option tarnaka
        %option kukatpally
        %option kothaguda
        %option yusfguda
        %option nanakram guda
        %option kphb
        %option ameerpet
        %br
        %br
      .pull-right
        %h6 Property Type
        %select.form-control
          %option{:value => "property type"} property type
          %option plots/land
          %option residentials
          %option agriculture land
          %option villas
          %option form house
        
       
    .col-sm-2
      %h6 Location
      %select.form-control
        %option{:value => "features"} city
        %option hyderbad
        %option mumbai
        %option banglore
        %option chennai
        %option pune

app/views/property/listurproperty.html.haml
.container
  .row
    %form.form-vertical
      %fieldset
        %br
        %label.radio-inline
          %input#inlineCheckbox1{:name => "types of operation", :type => "radio", :value => "resedentail"}/
          residentail
        %label.radio-inline
          %input#inlineCheckbox2{:name => "types of operation", :type => "radio", :value => "commercial"}/
          commercial
        %label.radio-inline
          %input#inlineCheckbox3{:name => "types of operation", :type => "radio", :value => "land"}/
          land
          
        %label.radio-inline
          %input#inlineCheckbox4{:name => "types of operation", :type => "radio", :value => "pg/rent"}/
          pg/rent
          %br
         
        %label{:for => ""}
        .row
          .col-xs-2.col-md-2
            %select.form-control
              %option{:value => "property type"} property type
              %option plots
              %option apartments
              %option independent houses
          .col-xs-2.col-md-2
            %select.form-control
              %option{:value => "features"} property features
              %option 1bhk
              %option 2bhk
              %option 3bhk
              %option 2 car parking
              %option swiming pool
          .col-xs-2.col-md-2
            %select.form-control
              %option{:value => "locality"} locality
              %option hi-tech
              %option tarnaka
              %option kukatpally
              %option kothaguda
              %option yusfguda
              %option nanakram guda
              %option kphb
              %option ameerpet
          .col-xs-2.col-md-2
            %select.form-control
              %option{:value => "property facing"} property facing
              %option north
              %option south
              %option east
              %option west
              %option south east
      %br
        .row
          .col-xs-2.col-md-2
            %input.form-control.input-extra.small{:name => "builtup area", :placeholder => "builtup area", :type => "text", :value => ""}/
            to
          .col-xs-2.col-md-2
            %input.form-control.input-extra.small{:name => "to", :placeholder => "builtup area", :type => "text", :value => ""}/
            sqft
      %br
        .row
          .col-xs-2.col-md-2.form-group
            %input#price.form-control{:autofocus => "", :name => "min price", :placeholder => "price", :price => "min price", :required => "", :type => "price"}min price
          .col-xs-2.col-md-2.form-group
            %input#price.form-control{:name => "max price", :placeholder => "price", :price => "max price", :required => "", :to => "", :type => "price"}max price
      %br
        .col-xs-2.col-md-2
          %select.form-control
            %option{:value => "transaction type"} transaction type
            %option resell
            %option new
            %option both
            %br
           
      %br
        .col-xs-2.col-md-2.form-group
          %input#image.form-control{:placeholder => "image", :required => "required", :title => "image", :type => "title"}image
          %br
          %button.btn.btn-primary.pull-right{:type => "browse"}
            browse
          %br
          %input#image.form-control{:placeholder => "title", :required => "required", :title => "title", :type => "title"}title
          %br
         
          %label{:for => "name"}
            description
            %textarea#description.form-control{:cols => "25", :name => "description", :placeholder => "description", :required => "required", :rows => "6"}
          %button.btn.btn-primary.pull-right{:type => "list"}
            list              
            
          
           

app/views/property/test.html.haml
.container
  .row
    .col-md-3
      hi
    .col-md-6
      hi
    .col-md-3
      hi

app/views/shared/_footer.html.haml
.footer
  .footer-left
    .title
      QuickLinks  
      = link_to "Contact us", contact_us_home_index_path, :class => 'btn btn-primary'
      
  .pull-right.text-muted
    = raw("<i class = 'glyphicon glyphicon-copyright-mark'></i>#{link_to 'OstryaLabs.', 'http://www.ostryalabs.com', :class =>"text-muted"} All Rights Reserved")
    = raw("<i class = 'fa fa-facebook fa-2x'></i>")
    = raw("<i class = 'fa fa-twitter fa-2x'></i>")
    = raw("<i class = 'fa fa-linkedin fa-2x'></i>") 
    = raw("<i class = 'fa fa-google-plus fa-2x'></i>") 
    = raw("<i class = 'fa fa-youtube fa-2x'></i>")

app/views/shared/_header.html.haml
.header
  .top-bar-one
    .top-bar-one-left
      = image_tag "logo6.jpg", :height => '55', :width => '50', :align => 'left', :class => "img-circle img-thumbnail", :style => "margin-left:3px;"
    .top-bar-one-middle
     
    .top-bar-one-right
      = link_to "LOGIN",login_home_index_path
      %span ||
      = link_to "REGISTER",registration_home_index_path
  .top-bar-two
    .top-bar-two-left
      = image_tag "logo6.jpg",:id =>"main-logo"
    .top-bar-two-right
      = link_to " Post Your Requirement",postrequirement_home_index_path, :class => 'btn btn-primary btn-cons'
      = link_to " List Your Property", listproperty_home_index_path, :class => 'btn btn-primary btn-cons'
      Location
      %select.selectpicker
        %option Hyderabad
        %option Chennai
        %option Mumbai
    